# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='open_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='openid'),
        ),
    ]
