# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.PositiveIntegerField(default=1000, verbose_name='账户余额'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='session_key',
            field=models.CharField(default=1, max_length=32, verbose_name='微信会话秘钥'),
            preserve_default=False,
        ),
    ]
