# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-17 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_comment_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_time', models.DateTimeField(auto_now_add=True, verbose_name='出价时间')),
                ('bid_price', models.PositiveIntegerField(verbose_name='出价金额')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='api.UserInfo', verbose_name='出价者')),
            ],
        ),
        migrations.CreateModel(
            name='CashDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '全场保证金'), (2, '单品保证金')], verbose_name='类型')),
                ('guarantee_sum', models.PositiveIntegerField(verbose_name='保证金额')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='名称')),
                ('image_url', models.CharField(max_length=256, verbose_name='封面')),
                ('video_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='拍品首页视频')),
                ('starting_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='起拍价')),
                ('present_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='当前出价价格')),
                ('transaction_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='成交价格')),
                ('bid_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='出价次数')),
                ('cash_deposit', models.IntegerField(verbose_name='单品保证金')),
                ('mark_up', models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='加价幅度')),
                ('browse_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='浏览次数')),
                ('turing_number', models.CharField(max_length=64, verbose_name='图录号')),
                ('particulars', models.TextField(verbose_name='拍品详情介绍')),
            ],
        ),
        migrations.CreateModel(
            name='CommodityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '轮播图'), (2, '详情介绍'), (3, '细节描述')], verbose_name='图片位置')),
                ('image_url', models.CharField(max_length=256, verbose_name='详情图片')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Commodity', verbose_name='拍品')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', models.CharField(max_length=32, verbose_name='内容')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Commodity', verbose_name='拍品')),
            ],
        ),
        migrations.CreateModel(
            name='SaleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=256, verbose_name='专场首页图片')),
                ('video_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='专场首页视频')),
                ('title', models.CharField(max_length=64, verbose_name='专场标题')),
                ('status', models.IntegerField(blank=True, choices=[(1, '预展中'), (2, '拍卖中'), (3, '结束')], default=1, null=True, verbose_name='状态')),
                ('starttime', models.DateTimeField(verbose_name='开始时间')),
                ('endtime', models.DateTimeField(verbose_name='结束时间')),
                ('cash_deposit', models.PositiveIntegerField(verbose_name='全场保证金')),
                ('Commodity_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='拍品数量')),
                ('bid_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='出价次数')),
                ('onlook_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='围观次数')),
                ('trading_volume', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='成交金额')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='salecategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.SaleCategory', verbose_name='拍卖专场'),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Commodity', verbose_name='拍品'),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='salecategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.SaleCategory', verbose_name='所属专场'),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.UserInfo', verbose_name='保证金缴纳者'),
        ),
        migrations.AddField(
            model_name='bidrecord',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Commodity', verbose_name='拍品'),
        ),
        migrations.AddField(
            model_name='bidrecord',
            name='salecategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.SaleCategory', verbose_name='所属专场'),
        ),
    ]
