# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-17 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_root'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enshrine', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Commodity', verbose_name='拍品')),
                ('salecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.SaleCategory', verbose_name='所属专场')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carerecord_user', to='api.UserInfo', verbose_name='保证金缴纳者')),
            ],
        ),
        migrations.AlterField(
            model_name='cashdeposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashd_deposit_user', to='api.UserInfo', verbose_name='保证金缴纳者'),
        ),
    ]
