# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-17 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20200117_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidrecord',
            options={'verbose_name_plural': '出价记录'},
        ),
        migrations.AlterModelOptions(
            name='carerecord',
            options={'verbose_name_plural': '收藏浏览记录'},
        ),
        migrations.AlterModelOptions(
            name='cashdeposit',
            options={'verbose_name_plural': '保证金缴纳记录'},
        ),
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name_plural': '拍品'},
        ),
        migrations.AlterModelOptions(
            name='commoditydetails',
            options={'verbose_name_plural': '拍品详细图片'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name_plural': '拍品详细参数'},
        ),
        migrations.AlterModelOptions(
            name='salecategory',
            options={'verbose_name_plural': '拍卖专场'},
        ),
        migrations.AlterField(
            model_name='cashdeposit',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Commodity', verbose_name='拍品'),
        ),
        migrations.AlterField(
            model_name='salecategory',
            name='cash_deposit',
            field=models.PositiveIntegerField(default=10000, verbose_name='全场保证金'),
        ),
    ]
