# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-17 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20200117_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='bid_count',
            field=models.PositiveIntegerField(default=0, verbose_name='出价次数'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='browse_number',
            field=models.IntegerField(default=0, verbose_name='浏览次数'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='mark_up',
            field=models.PositiveIntegerField(default=100, verbose_name='加价幅度'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='present_price',
            field=models.PositiveIntegerField(default=0, verbose_name='当前出价价格'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='starting_price',
            field=models.PositiveIntegerField(default=0, verbose_name='起拍价'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='transaction_price',
            field=models.PositiveIntegerField(default=0, verbose_name='成交价格'),
        ),
        migrations.AlterField(
            model_name='salecategory',
            name='Commodity_count',
            field=models.PositiveIntegerField(default=0, verbose_name='拍品数量'),
        ),
        migrations.AlterField(
            model_name='salecategory',
            name='bid_count',
            field=models.PositiveIntegerField(default=0, verbose_name='出价次数'),
        ),
        migrations.AlterField(
            model_name='salecategory',
            name='onlook_count',
            field=models.PositiveIntegerField(default=0, verbose_name='围观次数'),
        ),
        migrations.AlterField(
            model_name='salecategory',
            name='status',
            field=models.IntegerField(choices=[(1, '预展中'), (2, '拍卖中'), (3, '结束')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='salecategory',
            name='trading_volume',
            field=models.PositiveIntegerField(default=0, verbose_name='成交金额'),
        ),
    ]
