# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-17 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20200117_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salecategory',
            old_name='endtime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='salecategory',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
