# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-17 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20200117_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salecategory',
            old_name='Commodity_count',
            new_name='commodity_count',
        ),
        migrations.AlterField(
            model_name='carerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carerecord_user', to='api.UserInfo', verbose_name='浏览者'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='salecategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity', to='sale.SaleCategory', verbose_name='拍卖专场'),
        ),
        migrations.AlterField(
            model_name='salecategory',
            name='status',
            field=models.IntegerField(choices=[(1, '预展中'), (2, '拍卖中'), (3, '已结束')], default=1, verbose_name='状态'),
        ),
    ]
