# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_auto_20200117_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdeposit',
            name='order_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='order_status',
            field=models.IntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='payment_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='缴纳时间'),
            preserve_default=False,
        ),
    ]
