# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userinfo_open_id'),
        ('sale', '0009_auto_20200118_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(verbose_name='金额')),
                ('payment_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('order_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='订单号')),
                ('order_status', models.IntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='订单状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payorder_user', to='api.UserInfo', verbose_name='用户')),
            ],
        ),
        migrations.RemoveField(
            model_name='cashdeposit',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='cashdeposit',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='cashdeposit',
            name='payment_time',
        ),
        migrations.AlterField(
            model_name='salecategory',
            name='image_url',
            field=models.FileField(max_length=256, upload_to='', verbose_name='专场首页图片'),
        ),
    ]
