# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_auto_20200211_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecategory',
            name='preview_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预展时间'),
        ),
        migrations.AlterField(
            model_name='salecategory',
            name='status',
            field=models.IntegerField(choices=[(1, '预展中'), (2, '拍卖中'), (3, '已结束'), (4, '未开始')], default=1, verbose_name='状态'),
        ),
    ]
