# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0011_auto_20200211_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未开拍'), (2, '预展中'), (3, '拍卖中'), (4, '成交'), (5, '流拍')], default=1, verbose_name='状态'),
        ),
    ]
