# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adress'),
        ('sale', '0014_auto_20200212_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couponcash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_money', models.PositiveIntegerField(verbose_name='优惠金额')),
                ('limit_money', models.PositiveIntegerField(blank=True, null=True, verbose_name='满足金额')),
                ('status', models.PositiveIntegerField(choices=[(1, '有效'), (2, '过期'), (3, '已使用')], default=1, verbose_name='优惠券状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='有效期起始日期')),
                ('end_time', models.DateTimeField(verbose_name='失效日期')),
            ],
        ),
        migrations.RemoveField(
            model_name='pay_order',
            name='money',
        ),
        migrations.AddField(
            model_name='pay_order',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Adress', verbose_name='送货地址'),
        ),
        migrations.AddField(
            model_name='pay_order',
            name='due_money',
            field=models.PositiveIntegerField(null=True, verbose_name='应付金额'),
        ),
        migrations.AddField(
            model_name='pay_order',
            name='payment',
            field=models.PositiveIntegerField(null=True, verbose_name='实际付款金额'),
        ),
        migrations.AddField(
            model_name='couponcash',
            name='pay_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.Pay_Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='couponcash',
            name='salecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.SaleCategory', verbose_name='专场'),
        ),
        migrations.AddField(
            model_name='couponcash',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo', verbose_name='领取用户'),
        ),
    ]
