# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0015_auto_20200212_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_order',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Adress', verbose_name='送货地址'),
        ),
        migrations.AlterField(
            model_name='pay_order',
            name='due_money',
            field=models.PositiveIntegerField(default=0, verbose_name='应付金额'),
        ),
        migrations.AlterField(
            model_name='pay_order',
            name='payment',
            field=models.PositiveIntegerField(default=0, verbose_name='实际付款金额'),
        ),
    ]
