# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0017_auto_20200212_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_order',
            name='payment',
            field=models.PositiveIntegerField(verbose_name='实际付款金额'),
        ),
    ]
