# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0018_auto_20200212_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_order',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Adress', verbose_name='送货地址'),
            preserve_default=False,
        ),
    ]
