# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0019_auto_20200212_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdeposit',
            name='margin_balance',
            field=models.PositiveIntegerField(default=1, verbose_name='保证金余额'),
            preserve_default=False,
        ),
    ]
