# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0020_cashdeposit_margin_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_order',
            name='margin_balance',
            field=models.PositiveIntegerField(default=1, verbose_name='保证金金额'),
            preserve_default=False,
        ),
    ]
