# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0021_pay_order_margin_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositDeduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='金额')),
            ],
        ),
        migrations.CreateModel(
            name='DepositRefundRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, verbose_name='流水号')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '待退款'), (2, '已退款')], verbose_name='状态')),
                ('amount', models.PositiveIntegerField(verbose_name='退款金额')),
            ],
        ),
        migrations.RemoveField(
            model_name='pay_order',
            name='margin_balance',
        ),
        migrations.AddField(
            model_name='bidrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '竞价'), (2, '成交'), (3, '逾期未付款')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='pay_type',
            field=models.SmallIntegerField(choices=[(1, '微信'), (2, '余额')], default=1, verbose_name='支付方式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pay_order',
            name='commodity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sale.Commodity', verbose_name='拍品'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pay_order',
            name='deposit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sale.CashDeposit', verbose_name='保证金'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pay_order',
            name='twenty_four_task_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='24小时后的定时任务id'),
        ),
        migrations.AlterField(
            model_name='cashdeposit',
            name='status',
            field=models.IntegerField(choices=[(2, '全场保证金'), (1, '单品保证金')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未开拍'), (2, '预展中'), (3, '拍卖中'), (4, '成交'), (5, '流拍'), (6, '逾期未付款')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='pay_order',
            name='order_status',
            field=models.IntegerField(choices=[(1, '待支付'), (2, '代收货'), (3, '已完成'), (4, '逾期未付款')], default=1, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='depositrefundrecord',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.CashDeposit', verbose_name='保证金'),
        ),
        migrations.AddField(
            model_name='depositdeduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Pay_Order', verbose_name='订单'),
        ),
    ]
